language: node_js
node_js:
  - 9
  - 10
  - 11
matrix:
  allow_failures:
    - node_js: 11
os:
  - linux
  - centos
  - macosx
  - windows
cache:
  directories:
  - node_modules
services:
  - mongodb
install: 
  #  - npm i nsp -g
  - npm i
after_script:
  #  - nsp check
  - npm run testCoveralls
#notifications:
#  webhooks:
#    urls:
#      - $GITTER_IM_URL
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: never     # options: [always|never|change] default: always
