language: node_js
node_js:
  - 9
  - 10
  - 11
matrix:
  allow_failures:
    - node_js: 11
os:
  - linux
  - macosx
cache:
  directories:
  - node_modules
services:
  - mongodb
install: 
  - npm i
after_script:
  - npm run testCoveralls