language: node_js
node_js:
- 9
- 10
- 12
matrix:
  allow_failures:
  - node_js: 12
os:
- linux
- macosx
cache:
  directories:
  - node_modules
services:
- mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_52003b97e11e_key -iv $encrypted_52003b97e11e_iv -in deploy_rsa_node.enc -out deploy_rsa_node -d
install:
- npm i
after_script:
- npm run testCoveralls
jobs:
  include:
  - stage: deploy
    if: branch = master
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - scripts/deploy-travis.sh
