language: node_js
node_js:
  - 9
  - 10
  - 11
matrix:
  allow_failures:
    - node_js: 11
os:
  - linux
  - macosx
cache:
  directories:
  - node_modules
services:
  - mongodb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: 
  - yarn
after_script:
  - yarn testCoveralls